version: '3'

services:
  database: 
    image: postgres
    environment:
      POSTGRES_PASSWORD: root1234
    volumes:
      - "/Users/tuongvien/Documents/duongcao04/data/postgres-data:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@yangis.dev
      PGADMIN_DEFAULT_PASSWORD: pgadmin1234
    ports:
      - "5050:80"
    depends_on:
      - db